C0     = zeros(n,1);
C      = zeros(n,1);
CH0    = zeros(n,n_trace);
CH     = zeros(n,n_trace);
A      = zeros(n,1);
B      = zeros(n,1);
D      = zeros(n,1);
F      = zeros(n,1);
alpha1 = zeros(n,1);
beta   = zeros(n,1);
R      = linspace(0,1,n);
VV     = zeros(nt,1); %arrays for future storage of data and plotting
XXs    = zeros(nt,1);
XXs_in = zeros(nt,n_trace);
RRd    = zeros(nt,1);
tt     = zeros(nt,1);
UU     = zeros(nt,1);% array for undersaturation from first to last distance lenghth point 
Tsave  = zeros(nt,1);
ZrPls  = zeros(nt,1);
UH     = zeros(nt,n_trace);
CC     = zeros(nt,n);